### PR TITLE
Show nicer Executable Not Found Error

### LINKED ISSUE #612: Show nicer error if linter executable doesn't exist
I already know that the problem is that csslint is not at the specified path. But I thought it might be a good Idea to show some kind of warning instead of throwing an exception. 

**Atom Version**: 0.211.0
**System**: Mac OS X 10.10.3
**Thrown From**: [linter](https://github.com/AtomLinter/Linter) package, v1.0.4

### Stack Trace

Uncaught Error: ENOENT: no such file or directory, stat '/usr/local/bin/csslint'

```
At fs.js:846

Error: ENOENT: no such file or directory, stat '/usr/local/bin/csslint'
  at Error (native)
  at fs.statSync (fs.js:846:18)
  at Object.fs.statSync (ATOM_SHELL_ASAR.js:206:16)
  at LinterCsslint.Linter._cachedStatSync (/Users/egon/.atom/packages/linter/lib/linter.coffee:87:17)
  at LinterCsslint.Linter.getCmdAndArgs (/Users/egon/.atom/packages/linter/lib/linter.coffee:104:16)
  at LinterCsslint.Linter.lintFile (/Users/egon/.atom/packages/linter/lib/linter.coffee:145:24)
  at /Users/egon/.atom/packages/linter/lib/legacy.coffee:50:10
  at FSReqWrap.oncomplete (fs.js:77:15)

```

### Commands

```
     -8:36.1.0 core:delete (atom-text-editor.editor.is-focused)
     -8:26.2.0 core:copy (atom-text-editor.editor.is-focused)
     -8:24.9.0 core:paste (atom-text-editor.editor.is-focused)
  2x -8:17.1.0 core:backspace (atom-text-editor.editor.is-focused)
  2x -1:07.9.0 editor:newline (atom-text-editor.editor.is-focused)
  9x -1:02.5.0 core:backspace (atom-text-editor.editor.is-focused)
  2x -0:58.1.0 autocomplete-plus:confirm (atom-text-editor.editor.is-focused.autocomplete-active)
 10x -0:50.4.0 core:move-down (atom-text-editor.editor.is-focused.autocomplete-active)
     -0:45.2.0 autocomplete-plus:confirm (atom-text-editor.editor.is-focused.autocomplete-active)
     -0:44 core:move-right (atom-text-editor.editor.is-focused)
     -0:39.2.0 core:copy (atom-text-editor.editor.is-focused)
     -0:36.7.0 editor:newline (atom-text-editor.editor.is-focused)
     -0:36.5.0 core:paste (atom-text-editor.editor.is-focused)
     -0:32.4.0 autocomplete-plus:confirm (atom-text-editor.editor.is-focused.autocomplete-active)
     -0:11.7.0 core:save (atom-text-editor.editor.is-focused)
     -0:06.1.0 core:copy (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "themes": [
      "one-dark-ui",
      "solarized-dark-syntax"
    ],
    "disabledPackages": [
      "image-view",
      "background-tips",
      "language-go",
      "language-less",
      "language-property-list",
      "language-todo",
      "language-toml",
      "spell-check",
      "bookmarks",
      "welcome",
      "autoflow",
      "markdown-preview",
      "go-to-line",
      "language-c",
      "language-csharp",
      "language-java",
      "language-objective-c",
      "language-perl",
      "language-php",
      "language-python",
      "package-generator",
      "linter-tidy"
    ]
  },
  "linter": {
    "showInfoMessages": true,
    "subtleLinterErrors": [
      "jscs",
      "jshint"
    ],
    "clearOnChange": true,
    "showHighlighting": false
  }
}
```

### Installed Packages

```coffee
# User
atom-handlebars, v0.5.0
atom-ternjs, v0.6.4
color-picker, v2.0.7
linter, v1.0.4
linter-csslint, v0.0.13
linter-jscs, v1.12.0
linter-jshint, v0.1.6
linter-rubocop, v0.2.7
linter-xmllint, v0.0.6
pretty-json, v0.3.3
tabs-to-spaces, v0.11.0

# Dev
No dev packages
```

### PR DESCRIPTION
**Pull request by steelbrain**
We already had that error for normal executables, but not for node executables, this PR fixes that and also removes a bunch of redundant non-working code.
Fixes #612

### CODE REVIEW

**Comment by steelbrain** [comment]
Ready for a review people

File: lib/linter.coffee [hunk 1]
```diff
@@ -155,61 +155,42 @@ class Linter
...
-              Fully: =>
-                ignored.push @linterName
-                atom.config.set('linter.ignoredLinterErrors', ignored)
-              Partially: =>
-                subtle.push @linterName
-                atom.config.set('linter.subtleLinterErrors', subtle)
-        else
-          console.log warningMessageTitle
-        err.handle()
+        atom.notifications.addError("The linter binary '#{@linterName}' cannot be found.", {detail: "Linting has been halted.\nPlease install the linter binary or disable the linter plugin depending on it.\nMake sure to reload Atom to detect changes", dismissable: true})
```
Comment (iam4x) [inline lib/linter.coffee]: With coffeescript  you can have multine strings without `\n` seems cleaner (like the old code)

Comment (AsaAyers) [inline lib/linter.coffee]: selection_120

Also, this tells me the line is WAY too long. Even if you had to concatenate the strings together, this would need to be split.

**Comment by steelbrain** [comment]
Done.

**Comment by voxpelli** [comment]
Reported a bug caused by this PR: https://github.com/AtomLinter/Linter/issues/670 The assumption that all exit code `8`:s are missing node files unfortunately appears to be wrong.
